import { writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outDir = join(__dirname, '..', 'content', 'blog')
mkdirSync(outDir, { recursive: true })

const D = '2026-08-19'

const posts = [
  { slug: 'what-is-json', title: '什么是 JSON？JSON 入门详解', description: 'JSON 是一种轻量级数据交换格式，易于人读写、机器解析生成。本文介绍 JSON 的定义、特点与基本用法。', date: D, category: '基础', keywords: ['json', '什么是json', 'json入门'], intro: 'JSON（JavaScript Object Notation）是一种轻量级的数据交换格式，基于 JavaScript 语法的子集，采用完全独立于语言的文本格式。它易于人阅读编写，也易于机器解析生成，是当今 Web 开发中最常用的数据格式之一。', points: [{ h: 'JSON 的特点', p: 'JSON 采用键值对结构，支持字符串、数字、布尔、null、对象、数组六种数据类型，结构清晰、体积小、跨平台兼容性好。' }, { h: 'JSON 的用途', p: 'JSON 广泛用于 API 接口返回、配置文件、NoSQL 数据库存储、前后端数据交换等场景。' }], example: '{\n  "name": "JSONDog",\n  "version": "0.1.0",\n  "openSource": true\n}', tools: ['/format', '/validate'] },
  { slug: 'json-syntax', title: 'JSON 语法详解与规则', description: 'JSON 语法规则：键名与字符串必须双引号、逗号分隔、冒号连接、花括号对象、方括号数组、无尾逗号。', date: D, category: '基础', keywords: ['json语法', 'json规则', 'json格式'], intro: 'JSON 语法非常简洁，但有几条必须严格遵守的规则，违反任何一条都会导致解析失败。', points: [{ h: '基本规则', p: '键名与字符串必须用双引号包裹；键值对用冒号分隔；多个元素用逗号分隔；对象用花括号、数组用方括号；最后一个元素后不能有尾逗号。' }, { h: '常见错误', p: '使用单引号、键名未加引号、多余逗号、缺少引号是最高频的 JSON 语法错误。' }], example: '{"name": "张三", "age": 28, "hobbies": ["阅读", "编程"]}', tools: ['/validate', '/format'] },
  { slug: 'json-data-types', title: 'JSON 数据类型全览', description: 'JSON 支持六种数据类型：string、number、boolean、null、object、array，本文逐一详解。', date: D, category: '基础', keywords: ['json数据类型', 'json类型', 'json string'], intro: 'JSON 规范定义了六种数据类型，理解每种类型的特征是正确使用 JSON 的基础。', points: [{ h: '基本类型', p: 'string 字符串（双引号）、number 数字（整数或浮点）、boolean 布尔（true/false）、null 空值。' }, { h: '复合类型', p: 'object 对象（无序键值对集合）、array 数组（有序值列表），二者可无限嵌套。' }], example: '{"str": "text", "num": 42, "bool": true, "nil": null, "obj": {}, "arr": []}', tools: ['/validate', '/visualize'] },
  { slug: 'json-object', title: 'JSON 对象详解', description: 'JSON 对象是无序键值对集合，用花括号包裹，键必须是字符串，值可为任意类型。', date: D, category: '基础', keywords: ['json对象', 'json object', '键值对'], intro: 'JSON 对象是 JSON 最核心的结构，用花括号包裹的键值对集合，键名必须是双引号字符串。', points: [{ h: '对象结构', p: '对象由零或多个键值对组成，键值对之间用逗号分隔，键与值用冒号连接。键名唯一，重复键后值覆盖前值。' }, { h: '嵌套对象', p: '对象的值可以是另一个对象，形成多层嵌套，适合表达层级数据。' }], example: '{"user": {"name": "李四", "address": {"city": "上海"}}}', tools: ['/tree', '/format'] },
  { slug: 'json-array', title: 'JSON 数组详解', description: 'JSON 数组是有序值列表，用方括号包裹，元素可为任意类型且可混合。', date: D, category: '基础', keywords: ['json数组', 'json array', 'json列表'], intro: 'JSON 数组是有序的值列表，用方括号包裹，元素之间用逗号分隔，元素可以是任意 JSON 类型。', points: [{ h: '数组特性', p: '数组保持元素顺序，通过索引访问，可包含混合类型元素，也可嵌套对象或数组。' }, { h: '使用场景', p: '数组常用于表达列表、集合、分页数据、标签等有序数据。' }], example: '[1, "two", true, null, {"five": 5}, [6, 7]]', tools: ['/tree', '/format'] },
  { slug: 'json-nested', title: 'JSON 嵌套结构处理', description: 'JSON 支持对象与数组无限嵌套，本文讲解嵌套结构的设计、访问与扁平化技巧。', date: D, category: '基础', keywords: ['json嵌套', 'json嵌套结构', 'json深度'], intro: 'JSON 的强大之处在于对象与数组可以任意嵌套，表达复杂的层级数据，但过深嵌套也会带来处理难度。', points: [{ h: '合理嵌套', p: '建议嵌套深度控制在 3-4 层以内，过深不利于阅读与维护，可用扁平化工具简化。' }, { h: '路径访问', p: '嵌套值通过点路径或索引访问，如 user.address.city 或 list[0].name。' }], example: '{"a": {"b": {"c": {"d": 1}}}}', tools: ['/flatten', '/tree'] },
  { slug: 'json5-intro', title: 'JSON5 扩展语法介绍', description: 'JSON5 是 JSON 的超集，支持注释、单引号、尾逗号、多行字符串等扩展，更易读写。', date: D, category: '基础', keywords: ['json5', 'json5语法', 'json注释'], intro: 'JSON5 是 JSON 的扩展格式，在保持兼容的同时增加了注释、单引号、尾逗号等便利特性，深受开发者喜爱。', points: [{ h: 'JSON5 扩展', p: '支持单行 // 与多行 /* */ 注释、单引号字符串、对象数组尾逗号、无引号键名、十六进制数字等。' }, { h: '兼容性', p: 'JSON5 是 JSON 的超集，合法 JSON 必定是合法 JSON5，反之不成立。JSONDog 全工具支持 JSON5。' }], example: '{\n  // 这是注释\n  name: "JSONDog",\n  tools: ["format", "validate",]\n}', tools: ['/format', '/validate'] },
  { slug: 'json-vs-xml', title: 'JSON 与 XML 对比：该用哪个', description: 'JSON 与 XML 都是数据交换格式，JSON 更轻量、XML 更强大。本文从体积、可读性、解析速度等维度对比。', date: D, category: '基础', keywords: ['json vs xml', 'json xml对比', 'xml转json'], intro: 'JSON 与 XML 是两种主流数据交换格式，各有优劣，选择取决于场景。', points: [{ h: '主要差异', p: 'JSON 体积更小、解析更快、与 JavaScript 天然契合；XML 支持属性、命名空间、Schema 验证更完善。' }, { h: '选择建议', p: 'Web API、前后端交互首选 JSON；需要强结构验证、文档型数据可考虑 XML。' }], example: '{"person": {"name": "张三", "age": 28}}', tools: ['/format', '/validate'] },
  { slug: 'json-vs-yaml', title: 'JSON 与 YAML 对比', description: 'YAML 比 JSON 更简洁，靠缩进表示层级，支持注释。配置文件常用 YAML，API 常用 JSON。', date: D, category: '基础', keywords: ['json vs yaml', 'yaml转json', 'json转yaml'], intro: 'YAML 是 JSON 的超集，用缩进而非括号表示结构，更受配置文件青睐。', points: [{ h: '语法差异', p: 'YAML 用缩进表示层级，无需引号与逗号，支持注释与多行字符串；JSON 必须括号、引号、逗号。' }, { h: '使用建议', p: '配置文件用 YAML 更易读，数据交换用 JSON 更通用。可用工具互转。' }], example: 'name: JSONDog\nversion: 0.1.0\ntools:\n  - format\n  - validate', tools: ['/format', '/convert/yaml'] },
  { slug: 'json-vs-csv', title: 'JSON 与 CSV 对比', description: 'CSV 是表格数据格式，JSON 更灵活。扁平表格用 CSV 更紧凑，嵌套数据用 JSON。', date: D, category: '基础', keywords: ['json vs csv', 'csv转json', 'json转csv'], intro: 'CSV 是逗号分隔的表格格式，适合扁平结构化数据；JSON 适合嵌套与混合类型。', points: [{ h: '适用场景', p: 'CSV 适合导出 Excel、数据库表、扁平数据；JSON 适合 API、嵌套结构、配置。' }, { h: '互转注意', p: 'JSON 转 CSV 仅适合数组对象结构，嵌套数据需先扁平化。' }], example: 'id,name,age\n1,张三,28\n2,李四,30', tools: ['/flatten', '/convert/csv'] },
  { slug: 'json-vs-toml', title: 'JSON 与 TOML 对比', description: 'TOML 是语义明确的配置格式，比 JSON 更适合配置文件，支持注释与类型。', date: D, category: '基础', keywords: ['json vs toml', 'toml', '配置格式'], intro: 'TOML 旨在成为更好的配置文件格式，语义明确，支持注释与丰富类型。', points: [{ h: 'TOML 优势', p: '强类型、支持注释、日期时间类型、表结构清晰，适合复杂配置。' }, { h: '与 JSON 关系', p: 'TOML 可转 JSON，但 JSON 不支持注释，转回会丢失。' }], example: '[server]\nport = 8080\nhost = "localhost"', tools: ['/format', '/convert/toml'] },
  { slug: 'json-history', title: 'JSON 的历史与演变', description: 'JSON 由 Douglas Crockford 在 2000 年代初提出，现已成为 Web 数据交换事实标准。', date: D, category: '基础', keywords: ['json历史', 'json起源', 'douglas crockford'], intro: 'JSON 由 Douglas Crockford 在 2001 年前后提出并命名，源于 JavaScript 的对象字面量语法。', points: [{ h: '诞生背景', p: '为替代 XML 在 Web 数据交换中的笨重，Crockford 提炼出 JavaScript 语法的子集作为轻量数据格式。' }, { h: '成为标准', p: '2013 年 ECMA-404 标准化，2017 年 RFC 8259 发布，JSON 成为 Web API 事实标准。' }], example: '{"standard": "ECMA-404", "year": 2013}', tools: ['/format', '/validate'] },
  { slug: 'how-to-format-json', title: '如何格式化 JSON：美化与缩进', description: 'JSON 格式化（美化）是为 JSON 添加缩进与换行，提升可读性。本文介绍在线格式化方法。', date: D, category: '工具', keywords: ['json格式化', 'json美化', 'format json'], intro: 'JSON 格式化又称美化（beautify）或 pretty print，指为压缩的 JSON 添加缩进与换行，使其结构清晰易读。', points: [{ h: '为什么格式化', p: '压缩 JSON 单行难读，格式化后层级清晰，便于调试与排查错误。' }, { h: '如何操作', p: '粘贴 JSON 到格式化工具，选择缩进（2/4 空格或 Tab），一键生成美化结果。' }], example: '{"a":1,"b":{"c":2}}', tools: ['/format', '/minify'] },
  { slug: 'how-to-validate-json', title: '如何校验 JSON 语法', description: 'JSON 校验检查语法是否合法，定位错误行号并给出修复建议。', date: D, category: '工具', keywords: ['json校验', 'json验证', 'validate json'], intro: 'JSON 校验用于检查 JSON 文本是否符合语法规范，发现错误并定位到具体行列。', points: [{ h: '常见错误', p: '单引号、尾逗号、缺引号、缺逗号是高频错误，校验工具会指出位置与原因。' }, { h: '校验工具', p: '粘贴 JSON 即时校验，合法显示美化预览，非法显示错误行号与修复建议。' }], example: '{"bad": "missing quote}', tools: ['/validate', '/format'] },
  { slug: 'how-to-minify-json', title: '如何压缩 JSON：Minify', description: 'JSON 压缩去除所有空白与换行，减小体积，用于生产环境传输。', date: D, category: '工具', keywords: ['json压缩', 'json minify', 'compress json'], intro: 'JSON 压缩（minify）去除所有不必要的空白、换行与缩进，将 JSON 压成单行，减小传输体积。', points: [{ h: '压缩好处', p: '减小文件体积，加快网络传输，节省存储空间，适合生产环境。' }, { h: '开发建议', p: '开发时用格式化便于阅读，部署时用压缩优化性能。' }], example: '{"a":1,"b":[2,3],"c":{"d":4}}', tools: ['/minify', '/format'] },
  { slug: 'json-tree-viewer-guide', title: 'JSON 树查看器使用指南', description: 'JSON 树查看器将 JSON 以可折叠树形展示，支持搜索与路径复制，适合查看大型嵌套 JSON。', date: D, category: '工具', keywords: ['json树', 'json viewer', 'json查看器'], intro: 'JSON 树查看器将 JSON 渲染为可折叠的树形结构，层级一目了然，特别适合查看大型嵌套 JSON。', points: [{ h: '核心功能', p: '折叠展开节点、搜索键名高亮、点击复制 JSONPath 路径，快速定位数据。' }, { h: '适用场景', p: '查看 API 返回、调试嵌套配置、分析复杂数据结构。' }], example: '{"store": {"book": [{"title": "A", "price": 12}]}}', tools: ['/tree', '/jsonpath'] },
  { slug: 'json-editor-online', title: '在线 JSON 编辑器推荐', description: '在线 JSON 编辑器提供语法高亮、实时校验、行号，无需安装即可编辑 JSON。', date: D, category: '工具', keywords: ['json编辑器', 'json editor', '在线编辑json'], intro: '在线 JSON 编辑器让你在浏览器中直接编辑 JSON，提供语法高亮、行号、实时校验，无需安装任何软件。', points: [{ h: '编辑器功能', p: '语法高亮、实时校验、错误提示、复制下载，数据不出浏览器。' }, { h: '相比本地', p: '无需安装、跨设备可用、即时上手，适合临时编辑与快速校验。' }], example: '{\n  "name": "JSONDog",\n  "tools": ["editor"]\n}', tools: ['/editor', '/format'] },
  { slug: 'jsonpath-tutorial', title: 'JSONPath 查询语法教程', description: 'JSONPath 是按路径表达式查询 JSON 的语言，类似 XPath。本文讲解常用语法。', date: D, category: '工具', keywords: ['jsonpath', 'json path', 'json查询'], intro: 'JSONPath 是一种按路径表达式从 JSON 中提取数据的查询语言，语法类似 XPath，强大且简洁。', points: [{ h: '常用语法', p: '$ 根节点、. 子键、[] 数组索引、* 通配、.. 递归下降。如 $.store.book[0].title。' }, { h: '使用场景', p: '从大型 JSON 中精确提取字段，避免手动遍历，常用于 API 数据筛选。' }], example: '$.store.book[*].author', tools: ['/jsonpath', '/tree'] },
  { slug: 'json-to-yaml-tutorial', title: 'JSON 转 YAML 教程', description: '将 JSON 转换为 YAML 可获得更简洁的配置格式，本文介绍转换方法与注意事项。', date: D, category: '工具', keywords: ['json转yaml', 'json to yaml', 'yaml转换'], intro: '将 JSON 转为 YAML 可去除括号引号，用缩进表示层级，更适合配置文件。', points: [{ h: '转换规则', p: '对象转 YAML 键值对、数组转列表、字符串去引号、布尔数字原样。' }, { h: '注意点', p: 'YAML 对缩进敏感，转换后需检查缩进；特殊字符可能仍需引号。' }], example: '{"server": {"port": 8080, "host": "localhost"}}', tools: ['/convert/yaml', '/format'] },
  { slug: 'json-to-xml-tutorial', title: 'JSON 转 XML 教程', description: 'JSON 转 XML 用于与遗留系统交互，本文介绍转换规则与属性处理。', date: D, category: '工具', keywords: ['json转xml', 'json to xml', 'xml转换'], intro: '将 JSON 转为 XML 用于与遗留 Web Service 或配置系统交互，需注意结构映射。', points: [{ h: '转换规则', p: '对象转元素、键转子元素或属性、数组转重复元素、值转文本节点。' }, { h: '局限', p: 'JSON 无属性概念，转 XML 时键名既可作元素也可作属性，需约定。' }], example: '{"person": {"name": "张三", "age": 28}}', tools: ['/convert/xml', '/format'] },
  { slug: 'json-to-csv-tutorial', title: 'JSON 转 CSV 教程', description: 'JSON 转 CSV 用于导出表格，仅适合数组对象结构，嵌套需先扁平化。', date: D, category: '工具', keywords: ['json转csv', 'json to csv', 'csv导出'], intro: '将 JSON 转 CSV 用于导入 Excel 或数据库，仅适合扁平的数组对象结构。', points: [{ h: '转换条件', p: 'JSON 须为对象数组，每个对象的键作为列名，值作为单元格。' }, { h: '嵌套处理', p: '嵌套对象或数组需先扁平化为点路径键，否则无法映射到列。' }], example: '[{"id":1,"name":"a"},{"id":2,"name":"b"}]', tools: ['/convert/csv', '/flatten'] },
  { slug: 'json-to-typescript-tutorial', title: 'JSON 转 TypeScript 接口教程', description: '根据 JSON 自动生成 TypeScript interface 或 type，省去手写类型定义。', date: D, category: '工具', keywords: ['json转typescript', 'json to ts', 'json to interface'], intro: '根据 JSON 样本自动推断并生成 TypeScript 接口类型，省去手写 type 定义，提升开发效率。', points: [{ h: '生成原理', p: '遍历 JSON 结构，对象生成 interface，数组推断联合类型，基本类型映射 TS 类型。' }, { h: '使用建议', p: '提供有代表性的样本，确保类型推断准确；可设 readonly、export 选项。' }], example: '{"id": 1, "name": "x", "tags": ["a"]}', tools: ['/codegen/typescript', '/format'] },
  { slug: 'json-to-java-tutorial', title: 'JSON 转 Java POJO 教程', description: '根据 JSON 生成 Java POJO 类，含字段、getter/setter，用于快速建模。', date: D, category: '工具', keywords: ['json转java', 'json to pojo', 'json to java class'], intro: '根据 JSON 生成 Java POJO 类，自动推断字段类型并生成属性、构造器等，加速后端建模。', points: [{ h: '类型映射', p: 'string→String、number→Long/Double、boolean→Boolean、array→List、object→嵌套类。' }, { h: '生成选项', p: '可选包名、是否生成 getter/setter、Lombok 注解等。' }], example: '{"id": 1, "name": "x", "price": 9.9}', tools: ['/codegen/java', '/format'] },
  { slug: 'json-to-sql-tutorial', title: 'JSON 转 SQL 建表语句教程', description: '根据 JSON 结构生成 SQL CREATE TABLE 语句，推断字段类型，快速建表。', date: D, category: '工具', keywords: ['json转sql', 'json to sql', 'json建表'], intro: '根据 JSON 结构生成 SQL CREATE TABLE 语句，自动推断列类型，用于快速建表与数据建模。', points: [{ h: '类型推断', p: 'string→VARCHAR/TEXT、number→INT/BIGINT、boolean→TINYINT、日期→DATETIME。' }, { h: '适用场景', p: '快速为 JSON 数据设计表结构，导入数据库存储。' }], example: '{"id": 1, "name": "x", "created_at": "2026-01-01"}', tools: ['/codegen/sql', '/format'] },
  { slug: 'json-diff-compare', title: 'JSON 对比与差异分析', description: 'JSON 对比工具递归比较两段 JSON，输出新增、删除、修改的节点路径。', date: D, category: '工具', keywords: ['json对比', 'json diff', 'json compare'], intro: 'JSON 对比工具递归比较两段 JSON 的差异，输出每个新增、删除、修改节点的路径，便于排查变更。', points: [{ h: '对比规则', p: '对象按键名比较不区分顺序，数组按索引比较，基本值按相等比较。' }, { h: '使用场景', p: '对比 API 两次返回、排查配置变更、版本差异分析。' }], example: '{"a":1,"b":2} vs {"a":1,"c":3}', tools: ['/diff', '/format'] },
  { slug: 'json-mock-generator', title: 'JSON Mock 数据生成', description: '根据 JSON 样本结构生成随机 Mock 数据，保持类型与结构，用于测试。', date: D, category: '工具', keywords: ['json mock', 'mock数据', '假数据生成'], intro: 'Mock 数据生成器根据 JSON 样本结构生成随机假数据，保持类型与层级，用于测试与开发。', points: [{ h: '生成规则', p: '字符串生成随机串、数字生成随机数、布尔随机真假、null 保持、结构与嵌套保留。' }, { h: '使用场景', p: '前端联调、单元测试、接口演示、占位数据。' }], example: '{"id": 1, "name": "x", "active": true}', tools: ['/mock', '/format'] },
  { slug: 'json-schema-guide', title: 'JSON Schema 入门指南', description: 'JSON Schema 是描述 JSON 结构的规范，用于验证数据是否符合预期格式。', date: D, category: '工具', keywords: ['json schema', 'json schema生成', 'json验证'], intro: 'JSON Schema 是一种用 JSON 描述 JSON 结构的规范，可校验数据是否符合预期的类型、格式、约束。', points: [{ h: '核心概念', p: 'type 指定类型、properties 定义对象属性、items 定义数组元素、required 必填字段。' }, { h: '使用场景', p: 'API 请求响应校验、配置文件验证、数据契约定义。' }], example: '{"type": "object", "properties": {"name": {"type": "string"}}}', tools: ['/schema', '/validate'] },
  { slug: 'json-to-go-struct', title: 'JSON 转 Go struct 教程', description: '根据 JSON 生成 Go 结构体，含 json tag，用于 Go 后端快速建模。', date: D, category: '代码生成', keywords: ['json转go', 'json to golang', 'go struct'], intro: '根据 JSON 生成 Go 结构体定义，自动添加 json tag，用于 Go 后端反序列化建模。', points: [{ h: '类型映射', p: 'string→string、number→int/float64、boolean→bool、array→slice、object→嵌套 struct。' }, { h: 'tag 生成', p: '默认生成 `json:"key"` tag，可选 omitempty。' }], example: '{"id": 1, "name": "x"}', tools: ['/codegen/java', '/format'] },
  { slug: 'json-to-csharp-class', title: 'JSON 转 C# 类教程', description: '根据 JSON 生成 C# 类，用于 .NET 后端快速建模与反序列化。', date: D, category: '代码生成', keywords: ['json转csharp', 'json to c#', 'csharp class'], intro: '根据 JSON 生成 C# 类定义，自动推断属性类型，用于 .NET 序列化建模。', points: [{ h: '类型映射', p: 'string→string、number→int/double、boolean→bool、array→List、object→嵌套类。' }, { h: '使用建议', p: '可配合 Newtonsoft.Json 或 System.Text.Json 使用。' }], example: '{"id": 1, "name": "x", "price": 9.9}', tools: ['/codegen/java', '/format'] },
  { slug: 'json-to-python-class', title: 'JSON 转 Python 类教程', description: '根据 JSON 生成 Python dataclass 或 Pydantic 模型，用于 Python 后端建模。', date: D, category: '代码生成', keywords: ['json转python', 'json to pydantic', 'python dataclass'], intro: '根据 JSON 生成 Python dataclass 或 Pydantic 模型，用于 Python 后端数据校验与建模。', points: [{ h: '类型映射', p: 'string→str、number→int/float、boolean→bool、array→list、object→嵌套类。' }, { h: 'Pydantic 优势', p: 'Pydantic 提供运行时类型校验，适合 API 模型。' }], example: '{"id": 1, "name": "x", "tags": ["a"]}', tools: ['/codegen/java', '/format'] },
  { slug: 'json-to-rust-struct', title: 'JSON 转 Rust struct 教程', description: '根据 JSON 生成 Rust 结构体与 serde derive，用于 Rust 后端建模。', date: D, category: '代码生成', keywords: ['json转rust', 'json to rust', 'serde'], intro: '根据 JSON 生成 Rust 结构体，自动添加 serde derive 宏，用于 Rust 序列化。', points: [{ h: '类型映射', p: 'string→String、number→i64/f64、boolean→bool、array→Vec、object→嵌套 struct。' }, { h: 'serde 配置', p: '生成 #[derive(Serialize, Deserialize)] 与 rename_all 处理命名。' }], example: '{"id": 1, "name": "x"}', tools: ['/codegen/java', '/format'] },
  { slug: 'json-to-mybatis-mapper', title: 'JSON 转 MyBatis Mapper 教程', description: '根据 JSON 生成 MyBatis Mapper XML 与实体类，加速 Java 持久层开发。', date: D, category: '代码生成', keywords: ['json转mybatis', 'mybatis mapper', 'mapper xml'], intro: '根据 JSON 结构生成 MyBatis Mapper XML 与对应实体类，加速 Java 持久层开发。', points: [{ h: '生成内容', p: '实体类字段、resultMap 映射、基础 CRUD 的 SQL 语句。' }, { h: '使用场景', p: '根据接口返回 JSON 反推表结构与 Mapper，快速搭建持久层。' }], example: '{"id": 1, "name": "x", "age": 20}', tools: ['/codegen/mybatis', '/format'] },
  { slug: 'json-to-protobuf', title: 'JSON 转 Protobuf 教程', description: '根据 JSON 生成 Protobuf 消息定义，用于 gRPC 与跨语言序列化。', date: D, category: '代码生成', keywords: ['json转protobuf', 'protobuf', 'grpc'], intro: '根据 JSON 生成 Protobuf message 定义，用于 gRPC 服务与高效跨语言数据交换。', points: [{ h: '类型映射', p: 'string→string、number→int32/double、boolean→bool、array→repeated、object→嵌套 message。' }, { h: '优势', p: 'Protobuf 体积更小、解析更快、跨语言，适合高性能场景。' }], example: '{"id": 1, "name": "x"}', tools: ['/codegen/java', '/format'] },
  { slug: 'json-to-openapi', title: 'JSON 转 OpenAPI 规范教程', description: '根据 API 返回 JSON 生成 OpenAPI/Swagger 规范片段，用于接口文档化。', date: D, category: '代码生成', keywords: ['json转openapi', 'openapi', 'swagger'], intro: '根据 API 返回的 JSON 样本生成 OpenAPI/Swagger 规范的 schema 片段，用于接口文档化。', points: [{ h: '生成内容', p: 'components/schemas 定义、属性类型、示例值、必填字段。' }, { h: '使用场景', p: '快速为现有 API 补充 OpenAPI 文档，导入 Swagger UI。' }], example: '{"id": 1, "name": "x"}', tools: ['/codegen/java', '/format'] },
  { slug: 'json-to-markdown', title: 'JSON 转 Markdown 表格教程', description: '将 JSON 数组转为 Markdown 表格，用于文档展示与 README 编写。', date: D, category: '代码生成', keywords: ['json转markdown', 'json to md', 'markdown表格'], intro: '将 JSON 对象数组转为 Markdown 表格，键作为表头，值作为单元格，便于文档展示。', points: [{ h: '转换规则', p: '数组对象的键生成表头行，每个对象生成一行数据，用 | 分隔。' }, { h: '使用场景', p: '生成 README 表格、文档数据展示、API 字段说明。' }], example: '[{"name":"a","age":1},{"name":"b","age":2}]', tools: ['/convert/csv', '/format'] },
  { slug: 'json-to-excel', title: 'JSON 转 Excel 教程', description: '将 JSON 数据导出为 Excel xlsx 文件，用于数据分析与报表。', date: D, category: '代码生成', keywords: ['json转excel', 'json to xlsx', '导出excel'], intro: '将 JSON 数组导出为 Excel xlsx 文件，键作为列名，用于数据分析与报表分发。', points: [{ h: '转换条件', p: 'JSON 须为对象数组，每个对象的键作为列，值作为单元格。' }, { h: '使用场景', p: '导出业务数据、生成报表、与 Excel 用户协作。' }], example: '[{"id":1,"name":"a"},{"id":2,"name":"b"}]', tools: ['/convert/csv', '/flatten'] },
  { slug: 'json-to-graphql', title: 'JSON 转 GraphQL 教程', description: '根据 JSON 结构生成 GraphQL type 定义，用于 GraphQL 服务建模。', date: D, category: '代码生成', keywords: ['json转graphql', 'graphql type', 'graphql'], intro: '根据 JSON 结构生成 GraphQL type 定义，用于 GraphQL 服务的 schema 建模。', points: [{ h: '类型映射', p: 'string→String、number→Int/Float、boolean→Boolean、array→列表类型、object→嵌套 type。' }, { h: '使用场景', p: '快速为 GraphQL 服务生成 type 定义，减少手写。' }], example: '{"id": 1, "name": "x"}', tools: ['/codegen/java', '/format'] },
  { slug: 'json-pointer', title: 'JSON Pointer 详解', description: 'JSON Pointer (RFC 6901) 用斜杠路径定位 JSON 节点，如 /a/b/0。', date: D, category: '进阶', keywords: ['json pointer', 'rfc 6901', 'json路径'], intro: 'JSON Pointer 是 RFC 6901 定义的用斜杠分隔路径定位 JSON 节点的语法，是 JSON Patch 的基础。', points: [{ h: '语法', p: '以 / 开头，每段为键名或数组索引，如 /user/name、/list/0。特殊字符需转义。' }, { h: '与 JSONPath 区别', p: 'JSON Pointer 更简单，仅定位单一节点；JSONPath 支持通配与过滤，可返回多节点。' }], example: '/user/address/city', tools: ['/jsonpath', '/tree'] },
  { slug: 'json-patch', title: 'JSON Patch 操作详解', description: 'JSON Patch (RFC 6902) 用一组操作描述 JSON 变更，支持 add/remove/replace/move/copy/test。', date: D, category: '进阶', keywords: ['json patch', 'rfc 6902', 'json变更'], intro: 'JSON Patch 是 RFC 6902 定义的用操作数组描述 JSON 变更的格式，常用于增量更新与协同。', points: [{ h: '操作类型', p: 'add 添加、remove 删除、replace 替换、move 移动、copy 复制、test 测试。' }, { h: '使用场景', p: 'API 增量更新、协同编辑、版本差异表达。' }], example: '[{"op":"replace","path":"/name","value":"新值"}]', tools: ['/diff', '/format'] },
  { slug: 'json-web-token', title: 'JWT (JSON Web Token) 详解', description: 'JWT 是用 JSON 表示的紧凑令牌，用于身份认证与信息交换，由 header.payload.signature 组成。', date: D, category: '进阶', keywords: ['jwt', 'json web token', 'jwt认证'], intro: 'JWT（JSON Web Token）是用 JSON 表示的紧凑、URL 安全的令牌，广泛用于无状态身份认证。', points: [{ h: '结构', p: '由 header、payload、signature 三部分用点号连接，每部分 Base64URL 编码的 JSON。' }, { h: '使用流程', p: '登录返回 JWT，客户端携带请求，服务端验签解析 payload 获取用户信息。' }], example: 'header.payload.signature', tools: ['/encode', '/format'] },
  { slug: 'json-rpc', title: 'JSON-RPC 协议详解', description: 'JSON-RPC 是基于 JSON 的远程过程调用协议，轻量、无状态，支持 HTTP 与 WebSocket。', date: D, category: '进阶', keywords: ['json-rpc', 'json rpc', '远程调用'], intro: 'JSON-RPC 是一种基于 JSON 的轻量级远程过程调用协议，用 JSON 描述请求与响应。', points: [{ h: '消息结构', p: '请求含 jsonrpc、method、params、id；响应含 result 或 error 与对应 id。' }, { h: '使用场景', p: '区块链节点交互、内部微服务通信、WebSocket 接口。' }], example: '{"jsonrpc":"2.0","method":"getUser","params":[1],"id":1}', tools: ['/format', '/validate'] },
  { slug: 'json-api-spec', title: 'JSON:API 规范指南', description: 'JSON:API 是 RESTful API 的数据响应规范，统一资源、关系、分页、错误格式。', date: D, category: '进阶', keywords: ['json:api', 'json api规范', 'restful'], intro: 'JSON:API 是一套构建 RESTful API 数据响应的规范，统一了资源对象、关系、分页与错误的 JSON 结构。', points: [{ h: '核心约定', p: 'data 包含资源数组或单对象，relationships 描述关联，included 包含关联资源，meta 存元信息。' }, { h: '优势', p: '统一格式减少约定成本，客户端可通用化处理。' }], example: '{"data": [{"type": "user", "id": "1", "attributes": {"name": "x"}}]}', tools: ['/format', '/validate'] },
  { slug: 'json-serialization', title: 'JSON 序列化原理与库', description: 'JSON 序列化将对象转为 JSON 字符串，各语言有成熟库，本文介绍原理与选型。', date: D, category: '进阶', keywords: ['json序列化', 'json stringify', '序列化库'], intro: 'JSON 序列化指将内存对象转为 JSON 字符串，反序列化则相反，各语言均有成熟库支持。', points: [{ h: '主流库', p: 'JavaScript 内置 JSON、Java 用 Jackson/Gson、Python 用 json、Go 用 encoding/json。' }, { h: '注意点', p: '循环引用、大整数精度丢失、日期格式、Unicode 转义需特别处理。' }], example: 'JSON.stringify({a:1, b:[2,3]})', tools: ['/format', '/minify'] },
  { slug: 'json-deserialization', title: 'JSON 反序列化注意事项', description: 'JSON 反序列化将字符串转为对象，需注意类型丢失、精度、安全与错误处理。', date: D, category: '进阶', keywords: ['json反序列化', 'json parse', '反序列化'], intro: 'JSON 反序列化将 JSON 字符串解析为内存对象，过程中需注意类型、精度与安全。', points: [{ h: '常见问题', p: '大整数精度丢失（JS Number 限制）、日期需手动转换、类型信息丢失、非法 JSON 抛错。' }, { h: '安全', p: '避免 eval 解析（注入风险），使用 JSON.parse；注意原型链污染。' }], example: 'JSON.parse(\'{"a":1}\')', tools: ['/validate', '/format'] },
  { slug: 'json-performance', title: 'JSON 性能优化技巧', description: '大 JSON 解析与传输优化：压缩、流式解析、字段裁剪、二进制替代方案。', date: D, category: '进阶', keywords: ['json性能', 'json优化', '大json'], intro: '大 JSON 的解析与传输可能成为性能瓶颈，可通过多种手段优化。', points: [{ h: '优化手段', p: '传输前 minify、gzip 压缩、流式解析（SAX）、按需裁剪字段、考虑 Protobuf/MessagePack。' }, { h: '解析优化', p: '选用高性能库（如 simdjson）、Web Worker 避免阻塞主线程。' }], example: '{"big": "data..."}', tools: ['/minify', '/visualize'] },
  { slug: 'json-security', title: 'JSON 安全注意事项', description: 'JSON 处理需防注入、原型链污染、XSS、敏感信息泄露，本文列举安全要点。', date: D, category: '进阶', keywords: ['json安全', 'json注入', '原型链污染'], intro: '处理不可信 JSON 时需注意多种安全风险，避免注入与信息泄露。', points: [{ h: '风险点', p: '原型链污染（__proto__）、JSONP XSS、eval 解析注入、敏感字段泄露、大数 DoS。' }, { h: '防护', p: '用 JSON.parse 而非 eval、过滤危险键、限制大小、脱敏敏感数据。' }], example: '{"__proto__": {"polluted": true}}', tools: ['/validate', '/format'] },
  { slug: 'json-streaming', title: 'JSON 流式处理', description: '流式 JSON 解析（NDJSON、SAX）适合大文件与实时数据，避免一次性加载。', date: D, category: '进阶', keywords: ['json流式', 'ndjson', 'jsonl'], intro: '流式 JSON 处理适合大文件与实时数据流，避免一次性加载到内存。', points: [{ h: 'NDJSON', p: '每行一个独立 JSON 对象（JSON Lines），可逐行解析，适合日志与流数据。' }, { h: 'SAX 解析', p: '事件驱动解析，边读边处理，内存占用恒定，适合超大 JSON。' }], example: '{"id":1}\n{"id":2}\n{"id":3}', tools: ['/format', '/validate'] },
  { slug: 'json-in-api', title: 'JSON 在 API 中的应用', description: 'RESTful 与 GraphQL API 普遍用 JSON 作为请求响应格式，本文介绍最佳实践。', date: D, category: '场景', keywords: ['json api', 'restful json', 'api响应'], intro: 'JSON 是当今 Web API 事实标准格式，RESTful 与 GraphQL 均广泛采用。', points: [{ h: '响应设计', p: '统一状态码与错误结构、合理分页、字段命名一致、避免过深嵌套。' }, { h: '最佳实践', p: '用 HTTPS、压缩响应、版本化、文档化字段含义。' }], example: '{"code": 0, "data": {"id": 1}, "message": "ok"}', tools: ['/format', '/validate'] },
  { slug: 'json-as-config', title: 'JSON 作为配置文件', description: 'JSON 常用作配置文件，但不支持注释，可考虑 JSON5 或 JSONC 替代。', date: D, category: '场景', keywords: ['json配置', 'json config', 'jsonc'], intro: 'JSON 常用作配置文件（如 tsconfig、package.json），但不支持注释，编辑不便。', points: [{ h: '优缺点', p: '优点：标准、解析快、跨语言；缺点：无注释、无多行字符串、尾逗号非法。' }, { h: '替代方案', p: 'JSON5、JSONC（带注释）、YAML、TOML 更适合人工编辑的配置。' }], example: '{\n  "compilerOptions": {\n    "target": "es2020"\n  }\n}', tools: ['/format', '/validate'] },
  { slug: 'json-logging', title: 'JSON 日志格式最佳实践', description: '结构化 JSON 日志便于机器检索分析，本文介绍字段设计与采集。', date: D, category: '场景', keywords: ['json日志', '结构化日志', 'json log'], intro: '结构化 JSON 日志便于 ELK、Loki 等系统检索分析，优于纯文本日志。', points: [{ h: '字段设计', p: 'time、level、msg、service、traceId 等标准字段，业务字段扁平化。' }, { h: '采集', p: '每行一条 JSON（NDJSON），便于流式采集与解析。' }], example: '{"time":"2026-08-19T10:00:00Z","level":"info","msg":"started"}', tools: ['/format', '/minify'] },
  { slug: 'json-in-database', title: 'JSON 在数据库中的应用', description: 'PostgreSQL、MySQL、MongoDB 等支持 JSON 类型，可灵活存储半结构化数据。', date: D, category: '场景', keywords: ['json数据库', 'jsonb', 'json列'], intro: '现代关系数据库支持 JSON 类型字段，可灵活存储半结构化数据并查询。', points: [{ h: '各库支持', p: 'PostgreSQL 的 jsonb 可索引查询、MySQL 的 JSON 类型、MongoDB 原生 BSON。' }, { h: '使用建议', p: '频繁查询的字段提为列，JSON 存可变部分；注意索引与性能。' }], example: '{"profile": {"name": "x", "prefs": {"theme": "dark"}}}', tools: ['/format', '/validate'] },
  { slug: 'json-caching', title: 'JSON 缓存策略', description: 'JSON 响应可缓存于 CDN、Redis、本地，本文介绍缓存键设计与失效策略。', date: D, category: '场景', keywords: ['json缓存', 'api缓存', 'redis json'], intro: 'JSON 响应缓存可大幅提升性能，需合理设计缓存键与失效策略。', points: [{ h: '缓存层', p: 'CDN 缓存静态 JSON、Redis 缓存热点接口、浏览器缓存带 ETag。' }, { h: '失效策略', p: 'TTL 过期、版本号键、主动清除，注意一致性。' }], example: '{"key": "user:1:profile", "ttl": 3600}', tools: ['/minify', '/format'] },
  { slug: 'json-form-data', title: 'JSON 与表单数据转换', description: '前端表单常需与 JSON 互转，本文介绍序列化、嵌套表单与提交技巧。', date: D, category: '场景', keywords: ['json表单', 'form json', '表单序列化'], intro: '前端表单数据常需转为 JSON 提交 API，或将 JSON 回填表单，需处理嵌套与数组。', points: [{ h: '转换方式', p: 'FormData 遍历构建对象、name 用点路径表达嵌套、数组用 [] 后缀。' }, { h: '库推荐', p: 'qs、form-serialize、或框架内置（如 Vue v-model）。' }], example: '{"user": {"name": "x", "tags": ["a", "b"]}}', tools: ['/flatten', '/format'] },
  { slug: 'json-i18n', title: 'JSON 与国际化方案', description: 'JSON 是 i18n 资源文件常用格式，按语言分文件，键值映射文案。', date: D, category: '场景', keywords: ['json i18n', '国际化json', '多语言json'], intro: 'JSON 是国际化资源文件的常用格式，按语言分文件，键值对映射文案。', points: [{ h: '结构设计', p: '按语言分文件（en.json、zh.json），键用点路径或嵌套对象组织命名空间。' }, { h: '使用', p: '前端 i18n 库加载对应语言 JSON，按键取文案，支持插值与复数。' }], example: '{"welcome": "欢迎", "login": "登录"}', tools: ['/format', '/validate'] },
  { slug: 'json-testing', title: 'JSON 测试数据与断言', description: 'JSON 用于测试夹具与 API 断言，本文介绍组织、Mock 与断言技巧。', date: D, category: '场景', keywords: ['json测试', '测试数据', 'json断言'], intro: 'JSON 常用作测试夹具（fixture）与 API 断言数据，便于组织与维护。', points: [{ h: '夹具组织', p: '按场景分 JSON 文件，测试时加载作为输入或期望输出。' }, { h: '断言', p: '用 JSONPath 或深度比较断言响应，忽略可变字段（时间、ID）。' }], example: '{"expected": {"status": "ok", "code": 0}}', tools: ['/mock', '/diff'] },
  { slug: 'common-json-errors', title: '常见 JSON 错误及解决方法', description: '汇总 JSON 高频错误：单引号、尾逗号、缺引号、编码问题，附修复建议。', date: D, category: '错误调试', keywords: ['json错误', 'json报错', 'json修复'], intro: '使用 JSON 时会遇到多种高频错误，本文汇总原因与修复方法。', points: [{ h: '语法错误', p: '单引号改双引号、删除尾逗号、补全引号与逗号、检查括号匹配。' }, { h: '解析错误', p: 'Unexpected token 多为非法字符，Unexpected end 多为括号未闭合。' }], example: "{'key': 'value',}", tools: ['/validate', '/format'] },
  { slug: 'json-parse-error', title: 'JSON 解析错误排查指南', description: 'JSON.parse 报错时如何定位：看错误位置、检查行列、用校验工具。', date: D, category: '错误调试', keywords: ['json解析错误', 'json parse error', 'unexpected token'], intro: 'JSON.parse 抛错时需快速定位，本文给出排查步骤。', points: [{ h: '定位步骤', p: '看错误信息中的位置、用校验工具标红行列、检查该处字符与上下文。' }, { h: '常见原因', p: '非法字符、未转义引号、括号不匹配、混入 BOM 或非 JSON 内容。' }], example: '{"a": 1, "b": 2,}', tools: ['/validate', '/format'] },
  { slug: 'json-encoding-issues', title: 'JSON 编码问题：中文与 Unicode', description: 'JSON 中文与 Unicode 编码问题：\\u 转义、UTF-8 BOM、乱码排查。', date: D, category: '错误调试', keywords: ['json编码', 'json中文', 'json unicode'], intro: 'JSON 涉及中文与 Unicode 时易出现编码问题，需正确处理。', points: [{ h: '中文处理', p: 'JSON 允许直接写中文（UTF-8），也可能被转义为 \\uXXXX，两者等价。' }, { h: '乱码排查', p: '检查文件编码是否 UTF-8、有无 BOM、Content-Type 是否声明 charset。' }], example: '{"name": "中文", "emoji": "\\u4e2d"}', tools: ['/encode', '/format'] },
  { slug: 'large-json-files', title: '大 JSON 文件处理技巧', description: '处理大 JSON 文件：流式解析、分块、Web Worker、压缩，避免内存溢出。', date: D, category: '错误调试', keywords: ['大json', 'json大文件', 'json流式'], intro: '处理数十 MB 以上的 JSON 文件需特殊技巧，避免内存溢出与界面卡顿。', points: [{ h: '处理策略', p: '流式解析（SAX/NDJSON）、分块加载、Web Worker 后台处理、gzip 压缩传输。' }, { h: '工具建议', p: 'JSONDog 工具用 Web Worker 处理大文件，不阻塞界面。' }], example: '{"large": "..."}', tools: ['/visualize', '/format'] },
  { slug: 'json-deep-dive', title: 'JSON 深度解析：从语法到生态', description: '全面回顾 JSON：语法、类型、生态、工具、最佳实践，一文打通 JSON 知识体系。', date: D, category: '错误调试', keywords: ['json深度', 'json总结', 'json知识体系'], intro: '本文全面梳理 JSON 从语法、类型到生态工具的知识体系，助你打通 JSON。', points: [{ h: '知识脉络', p: '语法规则→六种类型→嵌套结构→序列化→校验→转换→代码生成→生态工具。' }, { h: '工具推荐', p: 'JSONDog 提供格式化、校验、转换、代码生成、可视化等全套 JSON 工具，纯前端零上传。' }], example: '{"summary": "JSON 知识体系"}', tools: ['/format', '/validate'] }
]

const render = (p) => `---
title: ${JSON.stringify(p.title)}
description: ${JSON.stringify(p.description)}
date: "${p.date}"
category: "${p.category}"
keywords: ${JSON.stringify(p.keywords)}
---

# ${p.title}

${p.intro}

${p.points.map((pt) => `## ${pt.h}\n\n${pt.p}`).join('\n\n')}

## 代码示例

\`\`\`json
${p.example}
\`\`\`

## 推荐在线工具

${p.tools.map((t) => `- [${t}](${t})`).join('\n')}

## 小结

${p.description} JSONDog 提供全套 JSON 在线工具，纯前端、零上传、中英双语，欢迎免费使用。
`

for (const p of posts) {
  writeFileSync(join(outDir, p.slug + '.md'), render(p), 'utf8')
}
console.log(`Generated ${posts.length} posts to ${outDir}`)